ashar/Controllers/ProjectController.cs
using ashar.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ashar.Controllers
{
    public class ProjectController : Controller
    {
        // *************************************  Prject Controller *************************************

        string connectionString = @"Data Source=DESKTOP-9928I97\MSSQLSERVER01;Initial Catalog=NGO;Integrated Security=True";
        private object productModel;


        // *************************************  Prject Index  *************************************

        [HttpGet]
        public ActionResult Index()
        {
            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("select * from Project", sqlCon);
                sqlDa.Fill(dtblProduct);
            }
            return View(dtblProduct);
        }

        // ************************************* INserting New Project  *************************************

        // GET: Project/Create
        public ActionResult Create()
        {
            return View(new ProjectModel());
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(ProjectModel projectModel)
        {
            // TODO: Add insert logic here
            using (SqlConnection sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                string query = "INSERT INTO Project VALUES(@ProName, @Start_date, @End_date)";
                SqlCommand sqlCommand = new SqlCommand(query, sqlConnection);
                sqlCommand.Parameters.AddWithValue("@ProName", projectModel.ProName);
                sqlCommand.Parameters.AddWithValue("@Start_date", projectModel.Start_date);
                sqlCommand.Parameters.AddWithValue("@End_date", projectModel.End_date);
                sqlCommand.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }


        // ************************************* Update A Project  *************************************

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            ProjectModel regModel = new ProjectModel();
            DataTable dataTableProduct = new DataTable();
            using (SqlConnection sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                string query = "Select * from Project Where ID = @ID";
                SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(query, sqlConnection);
                sqlDataAdapter.SelectCommand.Parameters.AddWithValue("ID", id);
                sqlDataAdapter.Fill(dataTableProduct);
            }
            if (dataTableProduct.Rows.Count == 1)
            {
                regModel.ID = Convert.ToInt32(dataTableProduct.Rows[0][0].ToString());
                regModel.ProName = dataTableProduct.Rows[0][1].ToString();
                regModel.Start_date = Convert.ToDateTime(dataTableProduct.Rows[0][2]);
                regModel.End_date = Convert.ToDateTime(dataTableProduct.Rows[0][3]);
                

                return View(regModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(ProjectModel projectModel  )
        {
            using (SqlConnection sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                string query = "UPDATE Project SET ProName = @ProName, Start_date=@Start_date, End_date=@End_date Where ID = @ID";
                SqlCommand sqlCommand = new SqlCommand(query, sqlConnection);
                sqlCommand.Parameters.AddWithValue("@ID", projectModel.ID);
                sqlCommand.Parameters.AddWithValue("@ProName", projectModel.ProName);
                sqlCommand.Parameters.AddWithValue("@Start_date", projectModel.Start_date);
                sqlCommand.Parameters.AddWithValue("@End_date", projectModel.End_date);
                
                sqlCommand.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }


        // ************************************* INserting New Project  *************************************

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {

            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "DELETE FROM Project WHERE ID = @ID";
                SqlCommand sqlCommand = new SqlCommand(query, sqlCon);
                sqlCommand.Parameters.AddWithValue("@ID", id);
                sqlCommand.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }
    }
}

ashar/Views/Project/Create.cshtml
@model ashar.Models.ProjectModel

@{
    ViewBag.Title = "Create";
}

<hr />
<h2 class="text-primary">ADD Project</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
   
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("View All Projects", "Index")
</div>

ashar/Views/Project/Edit.cshtml
@model ashar.Models.ProjectModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProjectModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ashar/Views/Project/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
}

<hr />
<h2 class="text-primary">ALL Projects</h2>
<hr />
<table class="table table-bordered table-striped">
    <tr>
        <th>Project Name</th>
        <th>Start Date </th>
        <th>End Date</th>
        <th></th>
    </tr>

    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>
            <td>@Model.Rows[i][1]</td>
            <td>@Model.Rows[i][2]</td>
            <td>@Model.Rows[i][3]</td>
            <td>
                <a href="@Url.Action("Edit", "Project", new {@id=@Model.Rows[i][0] })">Edit</a>
                <a href="@Url.Action("Delete", "Project", new {@id=@Model.Rows[i][0] })">Delete</a>
            </td>
        </tr>
    }
</table>

<a href="@Url.Action("Create","Project")">Add Project</a>